# Write your MySQL query statement below
SELECT S.STUDENT_ID,S.STUDENT_NAME, B.SUBJECT_NAME,COUNT(E.STUDENT_ID) AS ATTENDED_EXAMS 
FROM STUDENTS AS S
CROSS JOIN SUBJECTS AS B
LEFT JOIN EXAMINATIONS AS E ON E.STUDENT_ID=S.STUDENT_ID AND E.SUBJECT_NAME = B.SUBJECT_NAME
GROUP BY
S.STUDENT_ID,
S.STUDENT_NAME,
B.SUBJECT_NAME
ORDER BY S.STUDENT_ID  
;